[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "packageA"
version = "0.0.1"
dependencies = [ ]
description = ""
readme = "README.md"
requires-python = ">=3.1"
